### ISSUE TITLE
vignette: Project-migration.Rmd comments

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/readdst#32]
@erex this looks great. I make a few small modifications in deed800 and have some longer comments below... @lenthomas @LHMarshall please chime-in too!
# Using a project located on the local disk.

I see why you do this, but I'm not sure it's a good idea since that means for (at least) some people they need to create new directories and move files around in order to get the vignette to run. I would be inclined to ship as much as possible with `readdst`. At very least I'd be inclined to not include a path with spaces.

As a side note, if we are ever to submit this package to CRAN (which, as you know I am ambivalent about), this vignette would need to be modified to run on the CRAN test servers, meaning we need to include all the projects in `inst/` anyway...
# the `$env` environment

May be worth mentioning that environments are special in R and don't follow copy-on-pass semantics -- rather they have reference semantics. So things that happen to that environment within a function will not stay in that function, they will affect that object globally. This isn't really a problem except when people start writing their own functions that start messing with the data, but may be worth a warning.
# `mrds::` in front of functions

Although I think this is good practise, I think this probably confuses new users.
# `stratify-hazard`

Wouldn't:

``` r
stratify.hazard <- mrds::ddf(dsmodel=~cds(key="hr", formula=~1, adj.series="cos", adj.order=2),
                   meta.data=list(width=1.94000005722046,left=0), 
                   control=list(mono=TRUE, mono.strict=TRUE), method="ds", 
                   data=stratify.proj$'Half-normal cosine no stratification exact'$env$data)
```

be nicer as:

``` r
stratify.hazard <- ds(key="hr", formula=~1, adj.series="cos", adj.order=2,
                      truncation=1.94000005722046,
                   data=stratify.proj$'Half-normal cosine no stratification exact'$env$data)
```

?

Then we also get to show off `Distance` to folks who just look at this vignette? I also wrote an `AIC()` function for `Distance` that might be nice to introduce here when you're extracting the AIC...

**Comment by dill** [comment]
One other thing: it's probably worth explaining why we don't get ticks all the way down in the table of results from `test_stats`. I can provide some blurb for that if it's useful.

**Comment by erex** [comment]
Thanks for looking through this Dave.

I don't agree with the local directory business.  

I'm pitching `readdst` as a DistWin converter.  I'm showing that folks can use it on an in situ existing DistWin project rather than one that is magic-ed up by the writers of the package.  The 'path with spaces' issue stems from how DistWin sample projects are distributed, so a large fraction of the Windows users will have the projects they wish to translate living in "My Distance Projects" directory because that is the default directory when users open DistWin.

If you could add a paragraph about scoping and `$env`, that would be good.

I'll take away the `::` from calls to `mrds()`

I also prefer to keep separate the use of `ds()` from `Distance`.  I'm using the call translation that `readdst` created, rather than introduce a new package and new syntax.  Mention could be made of the existence of `Distance`, but that would raise the question in the user's mind, "Why didn't `readdst` produce a call to `ds()` rather than a call to `mrds()`?"

Likewise showing off `AIC()` in `Distance` gets away from the story being told about what `readdst` performs.

**Comment by lenthomas** [comment]
My feeling is that it is worth mentioning the existence of Distance and perhaps showing what the equivalent call to ds() is.  I think readers will be mellow about the fact that readdst doesn't (currently) produce calls to ds -- indeed you could mention that this facility may be added in a future version.

Likewise, I don't see the harm in mentioning the AIC function as an aside -- although I can see downsides also (e.g., more text on a different package to maintain in this one).  Up to the vignette writer, I say!

**Comment by dill** [comment]
Okay, if the directory structure makes sense on Windows then that's fine.

I've added the environment stuff as a footnote, since it's not really 
inline with the rest of the article and we don't want to confuse less R 
savvy folks. (c8f80e1)

No strong feeling either way on the Distance stuff.

**Comment by erex** [comment]
I recognise the Windows business is messy, but I think that is the audience we are trying to "bring into the fold".  Happy to make a passing comment that if folks aren't using a Windoze machine, they might have a different directory structure.  Having never used a Mac, what is that structure?  Does the emulator simply make a directory structure that feels like Windows; is there a "My Documents" and "My Distance Projects"?

**Comment by dill** [comment]
(I should add, I didn't regenerate the html file when I edited the Rmd, 
so that needs to be re-knitted)

**Comment by erex** [comment]
easy peasy

**Comment by dill** [comment]
I think it's worth mentioning the directory structure. I don't know 
whether it's worth trying to compromise on something that's both 
Windows-y and Mac-y as the inbetween will be foreign to both. Probably a 
quick note will be the most efficient solution.

I had an issue with path spaces when I try to run the vignette, so I 
think it's best to escape them as good practice, then all folks have to 
do is ensure the file structure is correct.

**Comment by erex** [comment]
Need to run off to tutor a Level 2 computing practical.  I may give vignette another brush at the weekend.

**Comment by erex** [comment]
@dill 
see if you approve of the revisions I've made to the vignette.  I've taken the light-hearted approach to Windows vs. Mac; see if you are OK.  If so, I'll load it onto the distancesampling.org site, so the JSS manuscript reference to it is accurate.

When you say 'escape path spaces',  does that mean backslashes?

instead of

```
sample.proj.dir <- paste0(home.dir, "/My Distance Projects/Sample Projects/")
```

replace with

```
sample.proj.dir <- paste0(home.dir, "/My\ Distance\ Projects/Sample\ Projects/")
```

In addition to comments made by you and Len, I've also amplified what the `test_stats` table contains.  I'm getting a queer warning out of `test_stats` I think, I've `warning=FALSE` it away for the moment.

**Comment by dill** [comment]
I tried to work out the spaces thing in a very basic way in [aad1e16](https://github.com/DistanceDevelopment/readdst/commit/aad1e16a0cb13e8a1ef64586e07c6b4fae860876) -- if the system is unix, then replace spaces with escaped spaces. I probably should have done this from the outset and fi tehre was a reason that I shouldn't, I've now forgotten...

Further edits coming in a moment.

**Comment by dill** [comment]
This looks good to me, a few minor edits in c809543. Given the change in the whitespace stuff, I've changed the text there but left in the caveat about spaces in general for completeness.

I think this is ready to go on the Distance site, which I'm happy to do or I can leave it to you.

**Comment by erex** [comment]
Thanks for the look-in.  I'll pop this up to distancesampling.org.  I made edits to the site last Friday (Tiago spotted dead links to "contacts.html" and I received Github admonishments about changes to their version of Jekyll (that I seem to have deleted).

**Comment by dill** [comment]
Okay, great, thanks for doing that.

IIRC from my own site, it's just a case of removing the markdown 
renderer entry from the config YAML file, as they've deprecated the one 
we use. I've not seen any difference in rendering elsewhere, so it 
should work fine, but may be worth checking those pages on the site.

cheers,
--dave

**Comment by erex** [comment]
Yes, I edited the _config.yml file and the website still functions.

**Comment by dill** [comment]
Can we close this?
